[project]
name = "schaukasten"
version = "0.1.0"
description = "A Queerreferat calendar parsing tool"
authors = ["Felix Broehan <it@queerreferat-aachen.de>"]
channels = ["conda-forge"]
platforms = ["linux-64"]
readme = "README.md"
repository = "https://github.com/FelixArt/schaukasten"

[tasks]

[dependencies]
python = "3.12.0.*"
pendulum = "2.1.2.*"
reportlab = "4.0.6.*"
icalendar = "5.0.10.*"
typer = "0.9.0.*"
requests = "2.31.0.*"
