name: Run python script + test
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Use three latest python versions
        python_version: [ "3.9", "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up python with version '${{ matrix.python_version }}'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Set locale
        run: |
          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8
      - name: Install packages
        run: |
          pip install -r requirements.txt
      - name: Run script
        run: |
          python main.py
          if [ -f event_overview*_de.pdf ];
          then
            echo -e "\033[0;32mGerman version exist.\033[0m"
          else
            echo -e "\033[0;31mGerman version does not exist.\033[0m"
            exit 1
          fi
          if [ -f event_overview*_en.pdf ];
          then
            echo -e "\033[0;32mEnglish version exist.\033[0m"
          else
            echo -e "\033[0;31mEnglish version does not exist.\033[0m"
            exit 1
          fi
          echo -e "\033[0;32mPipeline successful.\033[0m"
